### ISSUE TITLE
iOS 13 memory leak when presenting modally

### ISSUE THREAD

**Issue by fgeistert** [allaboutapps/ios-starter#11]
## Description
With iOS 13 came a new default modal presentation style `.automatic` when presenting a view controller modally. This allows the user to dismiss the view interactively.

See: https://developer.apple.com/documentation/uikit/uiviewcontroller/1621355-modalpresentationstyle

## Steps to reproduce
1) setup project
2) press "Login"
3) press "Debug Coordinator"
4) push as many view controllers as you want on the stack
5) dismiss the view using a swipe gesture

## Error Description
If you follow the steps above the memory allocated for the pushed view controllers will never be released, because the coordinator does not know about it.

**Comment by mbuchetics** [comment]
Fixed in `xcode11` branch. You can manually copy `Coordinator.swift` to your project.
