### ISSUE TITLE
Could not install @aaa/google-docs-i18n-strings

### ISSUE THREAD

**Issue by pmig** [allaboutapps/ios-starter#9]
@aaa/google-docs-i18n-strings seems not to be published on npm

```
npm ERR! code E404
npm ERR! 404 Not Found - GET https://registry.npmjs.org/@aaa%2fgoogle-docs-i18n-strings - Not found
npm ERR! 404 
npm ERR! 404  '@aaa/google-docs-i18n-strings@latest' is not in the npm registry.
npm ERR! 404 You should bug the author to publish it (or use the name yourself!)
```

**Comment by mbuchetics** [comment]
`google-docs-i18n-strings` is currently not open source and for internal use only. However, you can still use the `ios-starter`, just skip the `googleSheetId` parameter when asked by `cookiecutter`.

I updated the readme to clarify the installation steps. Thanks for pointing this out!
